### ISSUE TITLE
[Task] OAS Entity Operations

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#3]
## Entity Operations
Every entity needs to be accessible. Every entity also should have a possibility to interact with it. Define all entity types and give extending possibilities
#### Rules
- Keep REST and FS rules
- the assigned person
#### Tasks
- [x] Entity accessor
- [x] Entity types 
- [x] Entity interactions

**Comment by nbrugger-tgm** [comment]
## Entity Types
Which entity types except robots should be included?
Are Lasers and walls considerable as entities. They are theoretically part of the map but defining them as entities maybe offers a few possibilities.

**Comment by ghost** [comment]
## Entities

All objects which are static so which do not change their position should not be defined as entity.
