### ISSUE TITLE
[Task] Finalize OAS

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/game-controller#8]
## Finalize OAS
Do the last changes to the OAS (at least *V1*) do a detailed review and validate the file
#### Rules
- No OAS3.1 Validation Errors
- Take a look at the warnings
- Is the OAS meeting [conclusion rules](https://github.com/Local-Admin-BurgerKing/intsaller#oas)?
#### Tasks
- [x] Fix semantic,REST and FS rules
- [x] Validate OAS

**Comment by ComSubVie** [comment]
Maybe use https://github.com/Redocly/create-openapi-repo for writing/generation the documentation and https://github.com/Redocly/redoc to format/display the OpenAPI spec.

**Comment by nbrugger-tgm** [comment]
We will use *Redoc* as well as [*RapiDoc*](https://mrin9.github.io/RapiDoc/) and *SwaggerUI* to visualize the OAS.

The editor we are using is called [*Stoplight Studio*](https://stoplight.io/studio/)
